name: FastAPI MongoDB CI/CD

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:

  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      TRAEFIK_TAG: localhost
      TRAEFIK_PUBLIC_TAG: traefik-public
      TRAEFIK_PUBLIC_NETWORK: traefik-public
      STACK_NAME: maheswaran-full-stack-app-com
      DOMAIN: localhost
      DOCKER_IMAGE_BACKEND: backend
      DOCKER_IMAGE_FRONTEND: frontend
      DOCKER_IMAGE_CELERYWORKER: celeryworker
      PROJECT_NAME: Maheswaran Full Stack App

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          sh ./scripts/test.sh


  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: tests

    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Backend Image
        run: |
          docker build \
            -f backend/backend.dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-backend:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-backend:latest \
            ./backend


      - name: Build Frontend Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-frontend:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-frontend:latest \
            ./frontend


      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-backend:latest


      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-frontend:latest